# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Namn (För- och Efternamn)')),
                ('rsvp_answer', models.CharField(choices=[('Kommer', 'Kommer'), ('Kommer Inte', 'Kommer Inte')], max_length=40, verbose_name='OSA')),
                ('rsvp_datetime', models.TimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('dietary_restrictions', models.TextField(blank=True, verbose_name='Specialkost')),
                ('shuttle', models.CharField(choices=[('NEJ', 'Nej'), ('DIT', 'Bara dit'), ('DIT2300', 'Dit och hem 23:00'), ('DIT0030', 'Dit och hem 00:30'), ('DIT0200', 'Dit och hem 02:00')], max_length=40, verbose_name='Vill du åka buss? (om du vill åka buss på hemvägen ge gärna en gissning på vilken buss du vill ta)')),
            ],
        ),
    ]
